### ISSUE TITLE
call hasCapability and getting error

### ISSUE THREAD

**Issue by brianping7** [aholstenson/miio#10]
Hi, when i call the function "hasCapability“, i'm getting the following error.
  if(this.handle.hasCapability('power')) {
                 ^

TypeError: this.handle.hasCapability is not a function

i think it is because it doesn't initialized successfully, but i don't know why, their is no other log i can check, could you help? thanks.

**Comment by aholstenson** [comment]
How do you create and assign the value to `this.handle`?

**Comment by brianping7** [comment]
` this.handle = miio.device({ address: ip, token: token })
    .then(console.log(name + ' create'))
    .catch(console.error(name + ' failed'));`

i'm using device function.

**Comment by aholstenson** [comment]
`miio.device()` returns a promise that asynchronously resolves the device, so `this.handle` will still be pointing to that promise in the code you posted.

You probably want something like this instead:
```
miio.device({ address: ip, token: token })
  .then(device => this.handle = device)
  .catch(handleErrorConnectingToDevice);
```
