### ISSUE TITLE
Magnet - State is not fetched at startup

### ISSUE THREAD

**Issue by pierrecle** [aholstenson/miio#104]
With Aqara Door, my door is closed but at start `miio` return `true` when calling `isOpen()`.
Test code:
```javascript
const miio = require('./lib');

// Create a new device over the given address
miio.devices({cacheTime: 300}).on('available', reg => {
  if(!reg.token) {
    return;
  }
 
  const device = reg.device;
    if(device && device.matches('type:miio:gateway')) {
      const children = device.children();
      for(const child of children) {
        if(child.matches('type:miio:subdevice') && child.matches('cap:contact')) {
          child.on('opened', () => console.log(`${child.internalId} opened`));
          child.on('closed', () => console.log(`${child.internalId} closed`));
          child.isOpen().then((isOpen) => console.log(`${child.internalId} is open: ${isOpen}`));
        }
      }
    }
});
```

**Comment by aholstenson** [comment]
Just want to reference #101 here as a lot of the discussion about the network was there.

The state right now is that 0.15.3 will try to load the initial state via the developer API. For some users (like @pierrecle) the read-commands do not seem to receive any replies. In that case the device will be still be made available with a default state which is that it's not closed.

Feel free to add details to this issue if you are experiencing this as well. Use for example `DEBUG=\* miio inspect ipOfGateway` and post the output in this issue.
