### ISSUE TITLE
[REQUEST] device.state for Mi Robot Vacuum Cleaner to hold more states

### ISSUE THREAD

**Issue by jghaanstra** [aholstenson/miio#107]
In other thread you have mentioned that that way the state of the vacuum cleaner is handled is different now in 0.15.x. It's split into several different capabilities, such as one indicating if is charging, one if its cleaning, one if it has an error and so on.

I'm using miio in another app where I need to map the current state of the Mi Robot to a device capability as defined in the core of my home automation system (Homey) and the new implementation seems to limit me in doing so. I can access the state with device.state() but this only tells me if it's either cleaning or charging.

I'd like to see the state object expanded with all other possible states (like spotcleaning, docking, returning, etc.), preferably as a single string. Any chance this or something similar could be added?

**Comment by aholstenson** [comment]
I'll have a look at extending the vacuum with more details, a few more of the states should probably be available. In your case you could call `device.property('state')` as a work-around for now, it'll give the raw state of the vacuum (mapped to strings).

**Comment by jghaanstra** [comment]
Thanx, `device.property('state')` is sufficient for me!

**Comment by jghaanstra** [comment]
@aholstenson A user has reported an issue about the tracking of the device state within the repo of an app I have built using the miio library. The app is for a home domotica control system called Homey. It seems the tracking of the device state within the miio library is not updated fast enough. When someone starts the cleaner I need to update the device state within the home domotica controller but appearantly the device state in the miio library is not updated instantly as well after the robot has started cleaning. 

So my question is, how often is state property updated and is there a way to update it manually so I can keep it in sync with the state as registered within the domotica controller.

**Comment by aholstenson** [comment]
Polling is performed every 30 seconds for state. The issue here seems to be that the vacuum isn't refreshing the state after actions like many other devices. I'll add a fix and do a maintenance release of 0.15.

**Comment by aholstenson** [comment]
0.15.6 has now been pushed to NPM. The library now waits a second after activating or deactivating cleaning and then fetches the state. For my vacuum that seems to be enough time to update the state, and smaller timeouts seem to be 50/50 if the vacuum updates the state or not.

Do you think this is enough for your use case?

**Comment by jghaanstra** [comment]
Great, sounds like a proper solution for my use case! Thanx again.
