### ISSUE TITLE
maybe 'outlet' is a better type name for the plug things

### ISSUE THREAD

**Issue by Bluebie** [aholstenson/miio#11]
that's what they're called in homekit anyway.

**Comment by aholstenson** [comment]
That's a pretty good name. `switch` is used right now for both plugs, powerstrips and wall switches that all share the same functionality. It might make sense to split them into three types even though they all switch stuff on and off.

**Comment by aholstenson** [comment]
The new types are going to be:

* `power-switch`, for generic switchable devices
* `power-outlet`, for devices that are wall-mounted outlets (none supported right now)
* `power-plug`, for power plugs (either the Smart Socket Plug or the Aqara Plug right now)
* `power-strip`, for devices that are power strips

All of them have the capability `power-channel` and support one or more power channels like before.They all behave like the old `switch` so hopefully it will be easy to support all of them.

**Comment by aholstenson** [comment]
Released in 0.10.0.
