### ISSUE TITLE
Missing documentation to extract tokens

### ISSUE THREAD

**Issue by pierrecle** [aholstenson/miio#110]
I have 2 gateways, one works flowlessly, the other one is not recognized by miio. Extract from `discover`:
```
Device ID: 77249638
Model info: Unknown
Address: 10.0.0.8
Token: ???
Support: Unknown
```
I would like to set a token but the link to the documentation to extract tokens is broken.
Moreover, is there a way to provide the `developerKey`, as we know it when we enable local network on a gateway?

**Comment by Aure77** [comment]
If you are using Mi Home App (v5.0.19 or minor), you can use [MiToolkit](https://github.com/ultrara1n/MiToolkit) to extract token from this app (you need to connect your phone and activate USB debugging).

**Comment by aholstenson** [comment]
@pierrecle Unless the behavior of the gateway has also changed recently you should be able to reset it, connect to its WiFi and fetch the token that way. As far as I know (and this might be out of date) only the vacuum resets its token after setup in the Mi Home app. I've created #93 to track issues about the tokens, and I'll probably get around to updating the docs with information about how to extract tokens from the Android and iOS in a week or so.

Regarding just setting the developer key, it's a feature that isn't possible as this library only uses that API to read data and events. Things such as switching the gateway light on or off, switching power on or off for the in-wall light switches, and soon controlling alerts and alarms uses the same API as other devices. As long as `miio` can connect to the gateway the developer API is automatically activated, regardless if the user has activated it in the Mi Home app.

**Comment by pierrecle** [comment]
Thanks, I'll take a look.

**Comment by fergardi** [comment]
I'm also having problems with the Yeelight Color Bulb. I can discover the token after a reset and before adding the device to Mi Home app, but after that it seems to recreate the token and cannot connect to the device with the library. Any progress on that? Thanks in advance.

**Comment by jghaanstra** [comment]
@fergardi Yeelights don't require tokens to be added. The will be discovered during pairing.

**Comment by fergardi** [comment]
I tried the alternate method, using the Android abd backup feature, python-miio and miio-extract-tokens command to obtain the desired token and finally is working with your library. Thank you! Kind of messy in my opinion, any advances on the auto-extract-the-tokens feature?

**Comment by nickw444** [comment]
I'm an unjailbroken iOS user, and had success following this guide: https://github.com/jghaanstra/com.xiaomi-miio/blob/master/docs/obtain_token.md#non-jailbroken-ios-users
