### ISSUE TITLE
powerLoad and powerConsumed for WiFi power plug and power strip

### ISSUE THREAD

**Issue by jghaanstra** [aholstenson/miio#113]
It seems the powerLoad and powrConsumed capabilities for the WiFi power plug and power strip and not available anymore. Is this something on the todo list or has support been dropped completely?

**Comment by aholstenson** [comment]
They are currently available for the power plug connected to a gateway as it was the only one I was able to verify support on. It should be easy to add support for it if there any devices that also report these values. Any specific devices that support it?

**Comment by jghaanstra** [comment]
I was under the impression that all plugs supported this (I dont own any myself). Guess not then.
