### ISSUE TITLE
Vacuum zone cleaning

### ISSUE THREAD

**Issue by Luftloch80** [aholstenson/miio#119]
How to use the Feature?
Also working on gen1?

**Comment by aholstenson** [comment]
Thank you for opening an issue! 

Zone cleaning is something only supported by gen2 of the vacuum. `miio` does not support activating it as it depends on the map which is also not supported. My understanding is that the map is hidden away in the cloud service and `miio` deals with only the local API. This might change in the future but for now it's not possible to support it.

**Comment by kusmierz** [comment]
@Luftloch80 have a look at #133
