### ISSUE TITLE
could not get vacuum type

### ISSUE THREAD

**Issue by brianping7** [aholstenson/miio#12]
i run miio --discover, it shows below, and not able to get the type of vacuum

`Device ID: 55353665
Model ID: Unknown
Type: undefined
Address: 192.168.2.251 (rockrobo)
Token: null
Support: Unknown
`

**Comment by aholstenson** [comment]
The discovery of the vacuum is semi-broken at the moment as it doesn't share the same format of hostname as the other devices and in addition hides its token so we can't connect to it to figure out the type of device.

I'll see if I can add a workaround for this in the next release.

**Comment by aholstenson** [comment]
A workaround has been added for this issue in 0.9.0.
