### ISSUE TITLE
support for lumi.gateway.v3 exists but discover unknown

### ISSUE THREAD

**Issue by dneves** [aholstenson/miio#127]
This device is listed as supported in https://github.com/aholstenson/miio/blob/master/docs/devices/gateway.md but, in my case:
```
$ miio discover
 INFO  Discovering devices. Press Ctrl+C to stop.

Device ID: 56291293
Model info: yeelink.light.mono1
Address: 192.168.1.76
Token: e7826c871e7db98f74b63cddf45c6613 via auto-token
Support: At least basic

Device ID: 47390816
Model info: Unknown
Address: 192.168.1.65
Token: ???
Support: Unknown
```
for some reason miio is not able to identify my gateway.  
going at mi home app, 'Hub info' under gateway about menu, i confirm its a gateway v3, and the id checks.  
also, i think i enabled 'developer api', but my menu says 'wireless communication protocol' instead of 'lan' (as i found some instructions at https://docs.openhab.org/addons/bindings/mihome/readme.html)

after some experiments, doing this:
```
miio.device( { address: '192.168.1.65', token: '97dad275011ad8727e065dc5ad3dc471' } )
  .then(device => console.log('Connected to', device))
  .catch ( e => console.log( e ) );
```
prints
```
Connected to MiioDevice {
  model=lumi.gateway.v3,
  types=sensor, miio:gateway, miio,
  capabilities=illuminance, state, children
}
```
so, it can actually connect to it.

my question now is: is this normal behaviour? (discover unknown but able to connect directly)

**Comment by aholstenson** [comment]
Thanks for opening an issue!

I don't like the behavior, but yes its normal. Sometimes Miio will be able to discover the model of devices correctly, and sometimes it will fail. To discover the model Miio does a few things:

* It tries to lookup the hostname the device tried to register with on the network - which contains model info and identifier. If available this allow the model to be shown even without knowing the token.
* If a token is available, either via automatic discovery (support by some devices) or provided via the storage (which can be updated via the `miio` CLI) an information request will be sent to the device to discover the model.

If none of those things work Miio will just say it found some unknown device as there is not much else to do. You can make it display nicely for you by updating the token via `miio tokens update idOrIp --token your-token-here`.

Side note: Miio doesn't actually need you to enable the Developer API of gateways as long as it's able to connect to the gateway it'll automatically switch it on for you.

**Comment by Hypnos3** [comment]
I have try the command `miio tokens update idOrIp --token your-token-here` on two different computers

at the first It runs ok:
```
 INFO  Updating token for 98883039

 INFO  Connected to miio:98883039  - trying to change token

Token has been updated
```

```
Device ID: 98883039
Model info: lumi.gateway.v3
Address: 192.168.178.44
Token: c6bb......................................76b6a via stored token
Support: At least basic
```

At the second I get the following error:
```
 INFO  Updating token for 98883039

 INFO  Connected to miio:98883039  - trying to change token

 ERROR  Could not update token, double-check the given token
```

```
Device ID: 98883039
Model info: Unknown
Address: 192.168.178.44
Token: ???
Support: Unknown
```

Where is the token stored?
Can I copy any file from the first to the second to get there the came result?
