### ISSUE TITLE
Air Purifier 2 set_mode options (high, medium and low do not work)

### ISSUE THREAD

**Issue by mrking** [aholstenson/miio#13]
Just gave this library a quick 15 minute play around. Don't have any mobile emulators at the moment. I'll download and set one up some time this week. 

Modes that do no longer seem to work are: low, medium and high. Which makes some sense since the UI on the app in iOS doesn't have these sort of options?

**Comment by aholstenson** [comment]
Thank you for the report! Interesting to see that this might be different between different air purifiers.

What model id and firmware version does your Air Purifier 2 have? You can find the firmware version in the Mi Home app or by calling `device.management.info()`.

**Comment by mrking** [comment]
{ life: 396284,
  cfg_time: 0,
  token: '7c993d6c5692417ef8fece02c5da3317',
  mac: '28:6C:07:B8:38:26',
  fw_ver: '1.2.4_59',
  hw_ver: 'MC200',
  uid: 1554147845,
  model: 'zhimi.airpurifier.m1',
  wifi_fw_ver: 'SD878x-14.76.36.p79-702.1.0-WM',
  ap: { rssi: -29, ssid: 'A2', bssid: 'A0:04:60:77:0C:46' },
  netif: 
   { localIp: '192.168.1.129',
     mask: '255.255.255.0',
     gw: '192.168.1.1' },
  mmfree: 26400,
  ot: 'otu',
  otu_stat: [ 206, 184, 1160, 8, 1007, 9 ],
  ott_stat: [ 1, 3, 421, 198 ] }

**Comment by aholstenson** [comment]
Thanks! My Air Purifier is on 1.2.4_47 so it looks like those modes have been removed in the latest firmware. It makes sense as there are only three modes in the app and on the physical device.

I haven't seen any call that can be made to figure out the supported modes, so I'm leaning towards just removing them if they are no longer available.

**Comment by mrking** [comment]
Does your mi-home Android UI have options for low/medium/high? If so, I wonder how it determines to present them?

**Comment by aholstenson** [comment]
No, haven't seen it in Android or iOS. There are only three modes in the app, auto, silent or favorite. Long pressing on favorite allows one to set the level to run at when that mode is active.

**Comment by aholstenson** [comment]
These modes are no longer exposed by the air purifier as valid.
