### ISSUE TITLE
Error when trying to get token

### ISSUE THREAD

**Issue by mazaxaka** [aholstenson/miio#134]
Want to connect Xiaomi vacuum cleaner, but
When start miio --discover i get token, but after it add error 

`[root@ebridge alarm]# miio --discover
 INFO  Discovering devices. Press Ctrl+C to stop.

Device ID: 74262574
Model info: Unknown 
Address: 192.168.8.1 
Token: 776c396b6d5539737762644d42727154 via auto-token
Support: Unknown

(node:2646) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Call to device timed out
(node:2646) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

miio version 0.14.1
What i'm doing wrong?

**Comment by aholstenson** [comment]
Thanks for opening an issue!

0.14 is an old version of miio and 0.15 has improved discovery and token management. If you are not using some old Homebridge-plugin that requires miio to be globally installed and locked to 0.14 you can upgrade to 0.15 to manage your device.

**Comment by mazaxaka** [comment]
I use homebridge plugin. When trying to find device by 0.15.6 version nothing happend

**Comment by mazaxaka** [comment]
mazaxaka:~ mazaxaka$ npm install miio@latest
npm WARN saveError ENOENT: no such file or directory, open '/Users/mazaxaka/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/mazaxaka/package.json'
npm WARN mazaxaka No description
npm WARN mazaxaka No repository field.
npm WARN mazaxaka No README data
npm WARN mazaxaka No license field.

+ miio@0.15.6
updated 1 package in 1.999s
mazaxaka:~ mazaxaka$ miio --discover
 INFO  Discovering devices. Press Ctrl+C to stop.

^C
mazaxaka:~ mazaxaka$ miio --discover
 INFO  Discovering devices. Press Ctrl+C to stop.

Device ID: 82531725
Model info: Unknown 
Address: 192.168.8.1 
Token: 72643178575450446759626a6d744c58 via auto-token
Support: Unknown

(node:78344) UnhandledPromiseRejectionWarning: Error: Call to device timed out
    at Timeout.retry [as _onTimeout] (/usr/local/lib/node_modules/miio/lib/device.js:229:18)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
(node:78344) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:78344) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
