### ISSUE TITLE
wondering how to use sensor

### ISSUE THREAD

**Issue by brianping7** [aholstenson/miio#14]
it doesn't have any IP, it is just a sub device of gateway, how to initialize it? thanks.

**Comment by aholstenson** [comment]
If you connect to the gateway with `miio.device` you can then listen for events on the gateway to fetch the devices. Look at https://github.com/aholstenson/miio/blob/master/docs/devices/gateway.md for details.

The next release will introduce `miio.devices()` which will automatically connect to gateways and merge "top-level" devices and sub-devices together. The feature is documented at https://github.com/aholstenson/miio#discovering-devices but it's not yet published to NPM. But it will be released either today or in the next few days.
