### ISSUE TITLE
Getting blank  subdevice from gateway

### ISSUE THREAD

**Issue by brianping7** [aholstenson/miio#15]
i initialized the gateway successfully ,but there is no sub devices in the array. i can ensure there is sub device has connect with the gateway. thanks. 

":"function lookup4(address, callback) {\n  return lookup(address || '127.0.0.1', 4, callback);\n}","owner":"#<Socket>"},"_receiving":false,"_bindState":1,"type":"udp4","fd":null,"_reuseAddr":true},"devices":[]}}
  1: **this.device.devices = []**

**Comment by brianping7** [comment]
this.device = {"domain":null,"_events":{},"_eventsCount":0,"type":"gateway","model":"lumi.gateway.v3","capabilities":[],"address":"192.168.2.250","port":54321,

**Comment by aholstenson** [comment]
Devices become available asynchronously for the gateway, you need to listen for the events `deviceAvailable` and `deviceUnavailable` to keep track of devices being found and removed.

`device.on('deviceAvailable', subdevice => doSomethingWithSubdeviceHere)`

When `deviceAvailable` has triggered the device should be available in `devices` but it will not be available directly after connecting to the gateway.

**Comment by brianping7** [comment]
i try to set power off of a power-plug by using following code:
`that.device.on('deviceAvailable', subDevice => {
        if (subDevice.type == 'power-plug') {
            subDevice.setPower(1, false)
            .then(console.log(subDevice.name + " Power " + subDevice.power()))
            .catch(console.error(subDevice.name + " Failed to Power Off"));
        }`
i got following error..

`json.sid = options.sid;
                                 ^

TypeError: Cannot create property 'sid' on string '{"id":2,"method":"toggle_plug","params":["neutral_1","off"]}'
    at Gateway.call (/home/brianping7/work/home-jarvis/plugin/miHome/lib/device.js:173:13)
`

**Comment by aholstenson** [comment]
Thanks. The sub device code was broken in 0.11.0. Can you try 0.11.1 and see if works for you?

**Comment by brianping7** [comment]
above error not exist anymore,but still get some error.
`gateway init success
power-plug Failed :Error
power-plug Failed :Error
`
am i using the right input?
code:
`that.device.on('deviceAvailable', subDevice => {
        if (subDevice.type == 'power-plug') {
            subDevice.setPower(1, false)
            .then(power => console.log(subDevice.type + " Power " + power))
            .catch(err => console.error(subDevice.type + " Failed :" + err));
        }
        
        return;
      });`

**Comment by brianping7** [comment]
i use 0 as channel id to try, failed agagin
'''
subDevice.setPower(0, false)
'''

**Comment by aholstenson** [comment]
Hmm, I don't have access to the plug so hard for me to test any fixes.

What type of plug is it? There seems to be both a version that plugs into a socket and one that is an actual socket.

Could you try running `setPower` and log either `err.message` or `err` as its own argument? Something like this:

```
.catch(err => console.error(subDevice.type + " Failed :", err));
```

Hopefully one of those will output a more detailed error message that can help with figuring out what has gone wrong.

**Comment by brianping7** [comment]
Hi, i use `subDevice.setPower("0", false)` , the problem got fixed, thanks.

**Comment by aholstenson** [comment]
Good! Thank you for your issue reports!
