### ISSUE TITLE
Xiaomi Mi Flora Plant Sensor

### ISSUE THREAD

**Issue by astrojetson8** [aholstenson/miio#17]
I just noticed you had X next to Xiaomi Mi Flora Plant Sensor in documentation for devices , and I thought following might be useful to you
https://github.com/demirhanaydin/node-mi-flora

**Comment by aholstenson** [comment]
Thanks! I have a few of the Mi Flora sensors lying around and have looked at that project before. I decided against supporting them at this time and limit this project to devices that use the miIO-protocol and connect over WiFi.

That might change in the future though, but for now support for Bluetooth-devices is out of scope.
