### ISSUE TITLE
out of control

### ISSUE THREAD

**Issue by cnliri1** [aholstenson/miio#18]
Hello aholstenson

I raised an issue in homebridge-miio,my mi-plug is out of control and the detail described in [#19](https://github.com/Bluebie/homebridge-miio/issues/19). 

Below is my inspection log for the plug.
Thanks for your help.

Device ID: 351685
Model info: chuangmi.plug.v1 (power-plug)
Address: 192.168.1.102 (chuangmi-plug-v1_miio351685.lan)
Token: 15a04af260ef7cce0edcf6cca5f09e6c via auto-token
Support: At least basic

Firmware version: 1.2.4_7
Hardware version: MC200

WiFi: L Wi-Fi (70:73:CB:B9:AA:8F) RSSI: -51
WiFi firmware version: SD878x-14.76.36.p79-702.1.0-WM

Remote access (Mi Home App): UDP

Properties:
  - powerChannelMain: false
  - power: { main: false, usb: false }
  - powerChannelUsb: false

**Comment by aholstenson** [comment]
Thanks for the report! Can I ask you to run two other commands for me and paste the results as a comment?

The first command will attempt to switch the plug on and the second one will fetch the state of the plug.

To switch the plug on: `miio --control 351685 --command set_on --args '[]'`
To get the state of the plug: `miio --control 351685 --command get_prop --args '["on","usb_on"]'`

If the first command works we'll know the right command to power the plug on or off and the second will indicate if we can actually fetch if the device is on or not.

**Comment by cnliri1** [comment]
@aholstenson it works.

```
miio --control 351685 --command set_on --args '[]'
 INFO  Attempting to control 351685

 INFO  Got result:
0

miio --control 351685 --command get_prop --args '["on","usb_on"]'
 INFO  Attempting to control 351685

 INFO  Got result:
[
  true,
  true
]

```

**Comment by aholstenson** [comment]
Thank you! I think I can see what has gone wrong now. I'll push a fix for the issue in this project in the next few days, but it'll require some updates in `homebridge-miio` before you will be able to use your plug properly.

**Comment by aholstenson** [comment]
There is now a new release 0.12.0 that hopefully fixes this issue. Thanks for your help with reporting and debugging this issue!
