### ISSUE TITLE
Support for Xiaomi Philips zhirui downlight

### ISSUE THREAD

**Issue by chinswain** [aholstenson/miio#194]
I just purchased some Xiaomi ceiling lights for my bathroom - Is it possible to add support? (Happy to donate a unit). Token retrieved using Packet Sender.

https://uk.gearbest.com/ceiling-lights/pp_1830509.html

miio discover
> 
> Device ID: 92225854
> Model info: Unknown
> Address: 192.168.86.34
> Token: ???
> Support: Unknown

 node miio.js
> 
> TypeError: device.power is not a function
>     at getData (C:\Program Files\nodejs\miio.js:10:38)
>     at miio.device.then.device (C:\Program Files\nodejs\miio.js:25:3)

**Comment by DukeNuken** [comment]
The same problem here. After I connect to device wifi and send the info for the main wifi network the Philips downlight connect to my wifi but looks like change the token which not shown anymore. For me work the way when you make backup iPhone and then get open Mi Home database in that backup. There are can be found the tokens.
