### ISSUE TITLE
Support for Viomi Vacuum V2 robot cleaner

### ISSUE THREAD

**Issue by dhayab** [aholstenson/miio#244]
Hi, following your [guide](https://github.com/aholstenson/miio/blob/master/docs/missing-devices.md) to check whether miio can support a specific device, here is the transcript from `miio discover` for the Viomi V2 vacuum cleaner:

```
Device ID: <Redacted>
Model info: Unknown
Address: 192.168.0.5
Token: ???
Support: Unknown
```

After retrieving the token from the Mi Home app, I got more info (here from `miio inspect`):

```
Device ID: <Redacted>
Model info: viomi.vacuum.v6
Address: 192.168.0.5
Token: <Redacted> via stored token
Support: At least generic

Type info: miio
Capabilities:

Firmware version: 3.4.5_0021
Hardware version: Linux

WiFi: <Redacted> RSSI:

Remote access (Mi Home App): Maybe
```

I tried sending a few commands used by Roborock's vacuums (like find_me or get_status) but didn't get anything back.

I also tried to capture packets with Wireshark and the Bluestacks Android emulator, with no luck.

**Comment by dhayab** [comment]
After updating firmware to version 3.5.3_0030, the device cannot be discovered anymore using `miio discover`.

**Comment by FearlessSpiff** [comment]
I am on 3.5.3_0030 and can still `miio discover` I get the results as you discribed before. No way to send other commands to the vacuum. Would love to be able to do that.

**Comment by FearlessSpiff** [comment]
I traced the packets with my Fritzbox but unfortunately it's all encrypted.

**Comment by matthieulrg** [comment]
Same here... Help welcome
