### ISSUE TITLE
Time out when connecting with token

### ISSUE THREAD

**Issue by duindain** [aholstenson/miio#248]
I have been using miio for 3-4 years to get events from a  Xiaomi Purifier 2 and logging to Sql

Its been working great thankyou for developing the library

I recently had a new router for a few weeks with an alternate ip range, so I tried to refetch the token and config to keep it working in the meantime, this didn't work at the time

I'm now on a third router which is configured as the original was (same ip range, same wifi network) and I've successfully retrieved the token using miio discover by connecting my laptop to the purifier wifi AP with my firewall off and it is discovered almost instantly

When I attempt to connect to the device in node js it fails with a cannot auto get token with the following code
`
var address = '192.168.2.136';

miio.device({
        address: address,
}).then(device => {
        console.log('Connected to device');
        console.log(device);
}).catch(err => console.log('Error occurred:', err));

Error occurred: Error: Token could not be auto-discovered
    at Device._tokenResolve (/home/duindain/node_apps/node_modules/miio/lib/device.js:141:13)
    at Device._onMessage (/home/duindain/node_apps/node_modules/miio/lib/device.js:80:9)`

If i provide the token retrieved from miio discover, it fails with a timeout error
`const miio = require('miio');

var token = '7b8ac5c9d2b...';
var address = '192.168.2.136';
var model = 'zhimi.airpurifier.m1';

miio.device({
        address: address,
        token: token//,
        //model: model
}).then(device => {
        console.log("Connected to "+model);
        device.on('propertyChanged', e => {
                console.log("Property change detected: "+e.property +" was "+ e.oldValue +", now "+ e.value);
        });
        //device.destroy();
}).catch(error => console.log("Error " + error));

Error Error: Call to device timed out
`
I've tried with the model included and removed in the above code.
The purifier is on 192.168.2.136 with a static ip and I can ping it on the same network

I'm not sure if this is caused by the previous config conflicting with it? I couldn't find where the original token is stored

I did have to connect to the purifier wifi AP to get the token, running discover on the network the purifier is joining did not show the token
 
Node version v12.8.0
Miio version v0.15.6

Do you have any suggestions on what to try next please?

Thanks

**Comment by codenchip** [comment]
faced the same thing here!

**Comment by duindain** [comment]
I've tried the following now
Normal miio app latest version connecting and joining the network while scanning with miio discover
This failed as above

Scanning with miio discover and using miio configure to join the network for the purifier with 
miio configure id-or-address --ssid network-ssid --passwd network-password without using the app at all

This successfully joined the network but didn't work when using the token afterwards as above

I've tried downgrading the miio app to v5 but was unable to get the air purifier to join the network as the app didn't connect to their backend servers to load the screens

**Comment by duindain** [comment]
Using this guide [https://github.com/jghaanstra/com.xiaomi-miio/blob/master/docs/obtain_token.md](https://github.com/jghaanstra/com.xiaomi-miio/blob/master/docs/obtain_token.md) and some recent comments in other treads

- I've installed Xiaomi app 5.4.54
- Added the purifier
- Rebooted the phone
- Opened the text file SmartHome/logs/plug_DeviceManager/todays date.txt
- Found the token
- Added it to the node script and got 

> Error: Call to device timed out

I tried backing up the Mi Home app and opening the database to extract the token and the token field was empty so it seems the only way is from the text file with this version but the token that was in there wasen't correct

**Comment by duindain** [comment]
@dazhbog Ive seen your reply [here](https://github.com/aholstenson/miio/issues/93#issuecomment-531206729) could you be more specific please on how to get the token successfully please?

I think from your comments the process is the following?;
- Wipe the App data? do we need to delete the SmartHome folder too?
- Delete MiHome app
- Install 5.4.54
- Reboot the phone
- Reset the device
- Manually join the device to the network with Miio commands
- Open the app
- Click on the device? what does this mean the device wont exist in the app at this point?
- Open the text file SmartHome/logs/plug_DeviceManager/todays date.txt
- Extract the token and profit!

**Comment by dazhbog** [comment]
> @dazhbog Ive seen your reply [here](https://github.com/aholstenson/miio/issues/93#issuecomment-531206729) could you be more specific please on how to get the token successfully please?
> 
> I think from your comments the process is the following?;
> 
> * Wipe the App data? do we need to delete the SmartHome folder too?
> * Delete MiHome app
> * Install 5.4.54
> * Reboot the phone
> * Reset the device
> * Manually join the device to the network with Miio commands
> * Open the app
> * Click on the device? what does this mean the device wont exist in the app at this point?
> * Open the text file SmartHome/logs/plug_DeviceManager/todays date.txt
> * Extract the token and profit!

No need to go that complicated.

My steps
- Delete everything u can find. 
- Install the right version as mentioned. If the app doesn't load, restart phone (happened on one of my phones)
- Set up the device normally through the app (including the wifi step). Dont update for extra protection. Make sure u click on the device tile afterwards so that the app downloads the latest token, and creates the txt file with the token.
- Extract token and enjoy.

This way of setting the device in the app, allows u to control the device from the app and third party apps like miio.

**Comment by duindain** [comment]
Success
Thanks @dazhbog 

I followed these steps (I've previously gone into google settings and prevented the Xiaomi app from updating)

- Deleted Xiaomi App
- Deleted Xiaomi folder
- Deleted SmartHome folder
- Install Xiaomi App 5.4.54
- Run the app
- Select Singapore
- Click Add Nearby Device
- Sign in to the app
- Turn on Location
- Allow access to Location
- Select Air Purifier 2
- Added it (Failed three times eventually succeeded)
- Assigned to room
- Opened device in Xiaomi App
- let it connect (Doesnt load PM count anymore but all other stats show up, PM count does show up on summary screen just not when the device is open)
- Close everything
- Open the text file SmartHome/logs/plug_DeviceManager/todays date.txt
- Found the last instance of token
- Put it into my node script and I can connect again finally
