### ISSUE TITLE
Can't set option containing underscore

### ISSUE THREAD

**Issue by ben423423n32j14e** [aholstenson/miio#25]
The humidifier has options containing an underscore which appears to cause a problem with miio, example:

return device.call('set_led_b', ['bright']

Error output when attempting the above:

{ Error
    at Object.reject (/root/node_modules/miio/lib/device.js:213:13)
    at Device._onMessage (/root/node_modules/miio/lib/device.js:104:8)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:192:7)
    at UDP.onMessage [as onmessage] (dgram.js:547:8) code: -5001 }

**Comment by aholstenson** [comment]
If you check the `message` property of the error what does it say? I The code -5001 is invalid argument.

If the humidifier is similar to the air purifiers the led brightness is actually a number. The air purifiers use 0 = bright, 1 = dim, 2 = off.

**Comment by ben423423n32j14e** [comment]
I don't understand how to check the message property, how I suspect the _ is causing the issue is this:

return device.call('set_led', ['bright'])

produces this error message:
{ Error: Method not found.
    at Object.reject (/root/node_modules/miio/lib/device.js:213:13)
    at Device._onMessage (/root/node_modules/miio/lib/device.js:104:8)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:192:7)
    at UDP.onMessage [as onmessage] (dgram.js:547:8) code: -32601 }

return device.call('set_led_b', ['bright']

produces this message:
{ Error
at Object.reject (/root/node_modules/miio/lib/device.js:213:13)
at Device._onMessage (/root/node_modules/miio/lib/device.js:104:8)
at emitTwo (events.js:106:13)
at Socket.emit (events.js:192:7)
at UDP.onMessage [as onmessage] (dgram.js:547:8) code: -5001 }

**Comment by ben423423n32j14e** [comment]
You are correct the current LED status on my unit is: 2

I still receive the error message when attempting to send the command through miio.

The only commands I can't send are to those with the additional _ in the name.

set_led_b

**Comment by aholstenson** [comment]
The humidifier might do something special here. Could you run your code while setting the environment flag `DEBUG` to `miio*`? Something like this: `DEBUG=miio* node pathtoscript.js`

You should get lots of debug information about data sent and received, the bit from where you can see some JSON with your call until you get some other JSON as a reply can help with figuring out what's going wrong.

**Comment by ben423423n32j14e** [comment]
This is interesting, 2 is the current known state of the LED from the device status, yet it rejected it:

  miio.device.[192.168.0.95] -> (2) {"id":1,"method":"set_led_b","params":["2"]}
  miio.device.[192.168.0.95] <- Message: `{"error":{"code":-5001,"message":"invaild_arg"},"id":1}

**Comment by ben423423n32j14e** [comment]
BINGO, got it working :)

return device.call('set_led_b', [JSON.parse(thirdarg)])

I'll update the humidifier doc once I've tested the remaining options.

**Comment by aholstenson** [comment]
Alright! Looks like you were sending a string when the device wants a number. Most of the Mi devices are picky about that.

In the current `master` there is some new documentation and a device implementation to make interacting with the humidifier easier. Such as being able to call `device.setLedBrightness('off')` instead of using `call` directly.

When you know what the other options do you can open an issue and describe what you found or try to add it to the implementation in `lib/devices/humidifier.js`.
