### ISSUE TITLE
Has anyone tested it with Air Purifier 2s EU version?

### ISSUE THREAD

**Issue by dottoreFell** [aholstenson/miio#258]
Air Purifier 2s isn't on the supported devices list, but it works fine for me. I have CN version, but I want to buy next two units, this time EU version. Will they work with miio so well as CN version?

**Comment by kwesolowski** [comment]
Works for me:


Device ID: XXXXX
Model info: zhimi.airpurifier.mc1
Address: 192.168.0.6
Support: At least generic

**Comment by dottoreFell** [comment]
I have bought this version:

Device ID: 132218784
Model info: zhimi.airpurifier.mc1
Address: 192.168.1.148
Token: ???
Support: At least generic

I am connecting, but Purifier won't react to commands, capability list is empty:

 Connected to MiioDevice {
  model=zhimi.airpurifier.mc1,
  types=miio,
  capabilities=
}


`miio.device({ address: '192.168.1.148', token: tokens })
    .then(device => {
        device.temperature()
            .then(temp => console.log(temp))
    })
    .catch(err => console.log(err));`

TypeError: device.temperature is not a function
    at miio.device.then.device (/home/michal/source/home_assistant/purifier2_IO.js:88:12)

Any ideas?

**Comment by kwesolowski** [comment]
Looks like missing token (unless you actually replaced real token with ???)

**Comment by dottoreFell** [comment]
tokens is variable that contains device token. If token was missing then the part of code within .then block (device.temperature call) wouldn't be executed at all.

In this case I am able to connect but capability list is empty and therefore the rest of commands doesn't work.


EDIT: Working chinese version has firmware 1.4.3_13108, my second eu purifier has 1.4.3_21104

**Comment by kwesolowski** [comment]
When you test this do you have merged https://github.com/aholstenson/miio/pull/220?

**Comment by dottoreFell** [comment]
> When you test this do you have merged #220?

@kwesolowski 
I manually edited models.js and added missing line. It is working fine. I am new to git and programming, so tommorow I will take a closer look at this and try to do merge. Also I will investigate why I haven't found Your solution before and probably learn something new about github.
 Thanks a lot!

**Comment by kwesolowski** [comment]
@aholstenson Second person happy with mc1. Can you pick few people who were active here to merge at lest such simple PRs? I can help a bit as well... Its too great project to keep private fork :(

**Comment by dottoreFell** [comment]
What could we do? Isn't the project maintainer who can merge PRs?

**Comment by kwesolowski** [comment]
Yes, project maintainer or people which he gave power to (i.e. write
permission in the "master" repo).

Pozdrawiam/Regards
Krzysztof Wesołowski

tel. +48 721 337 238
http://www.rainlabs.eu

**Comment by kwesolowski** [comment]
Can you refer to this issue in pull request?
