### ISSUE TITLE
Support for Air Purifier 3/3H (zhimi.airpurifier.mb3)

### ISSUE THREAD

**Issue by petrkotek** [aholstenson/miio#264]
Today, I got the newest Xiaomi's Air Purifier delivered - it's Xiaomi Air Purifier 3/3H (and identifies itself as `zhimi.airpurifier.mb3`).

Soon after, I found out it's not supported by miio yet (and therefore neither by Home Assistant which I use).

I'm a developer myself and happy to contribute & implement the support for it. I'll try to work on this in my spare time (kicking off by reading instructions here https://github.com/aholstenson/miio/blob/master/docs/missing-devices.md).

If somebody else has this device, I'd be happy to collaborate on the implementation.

**Comment by petrkotek** [comment]
Related efforts:
- https://github.com/rytilahti/python-miio/issues/543
- https://github.com/YinHangCode/homebridge-mi-airpurifier/issues/36

**Comment by petrkotek** [comment]
I'm now to turn ON/OFF the device:
```
miio protocol call 192.168.0.22 set_properties '[{"did":"MYDID","piid":2,"siid":2,"value":true}]' #ON
miio protocol call 192.168.0.22 set_properties '[{"did":"MYDID","piid":2,"siid":2,"value":false}]' #OFF
```

Change fan speed, e.g.:
```
miio protocol call 192.168.0.22 set_properties '[{"did":"MYDID","siid":2,"piid":4,"value":1}]' # level 1
miio protocol call 192.168.0.22 set_properties '[{"did":"MYDID","siid":2,"piid":4,"value":2}]' # level 2
miio protocol call 192.168.0.22 set_properties '[{"did":"MYDID","siid":2,"piid":4,"value":3}]' # level 3
```

(Big thanks to https://github.com/rytilahti/python-miio/issues/543#issuecomment-531528340 / https://github.com/rytilahti/python-miio/issues/543#issuecomment-544745035)

**Comment by petrkotek** [comment]
I just realised that Home Assistant actually uses https://github.com/rytilahti/python-miio

As I don't really need the support in this library, I'm closing this thread.

**Comment by mouth4war** [comment]
Petrkotek: this library is used by homebridge so if you ever need to get proper homekit integration of your 3h (as air purifier not just fan), you'll need this library then.
