### ISSUE TITLE
Smartmi Evaporative Air Humidifier - Downgrade

### ISSUE THREAD

**Issue by lenisko** [aholstenson/miio#272]
Hey guys!

I have problem with my smartmi humidifier.
It's reporting "insufficient water" after upgrade to 1.6.7 (I think that's the cause, as it was working before). Device is not able to start due to this error.

Model: CJXJSQ02ZM / V1.0-180508-Y

Is there any way to downgrade to older firmware using miio or other software/method?

Cheers

**Comment by isabellaalstrom** [comment]
I see this is closed. Did you find solution?

**Comment by lenisko** [comment]
@isabellaalstrom To be honest it got fixed itself... unsure why.
