### ISSUE TITLE
miio --discover fails to recognize gateway 2

### ISSUE THREAD

**Issue by pointbre** [aholstenson/miio#28]
First of all, thanks for your fantastic work.

BTW, I believe I have a Xiaomi Gateway 2 (DGNWG02LM) but miio is not recognizing it properly.

$ miio --discover --sync
 INFO  Discovering devices. Press Ctrl+C to stop.

Device ID: 44605366
Model info: Unknown 
Address: 192.168.31.68 
Token: db25a7539e35bc660f201eb69958e75f via auto-token
Support: Unknown

Device ID: 52269167 ---> This is Xiaomi Gateway 2
Model info: Unknown 
Address: 192.168.31.207 
Token: 607a194ccaf7e9c7d8fca7ab8371630d via auto-token
Support: Unknown

Device ID: 158d000157382e --> Temp & Humidity sensor connected to the gateway
Model info: lumi.sensor_ht (sensor)
Address: Owned by 52269167
Token: Automatic via parent device
Support: At least basic

Device ID: 158d0001874c26 --> PIR sensor connected to the gateway
Model info: lumi.motion (motion)
Address: Owned by 52269167
Token: Automatic via parent device
Support: At least basic

Device ID: 158d00012ca74c --> Wireless switch connected to the gateway
Model info: lumi.switch (controller)
Address: Owned by 52269167
Token: Automatic via parent device
Support: At least basic

Device ID: 158d00014d3826 --> Window/door magnetic sensor connected to the gateway
Model info: lumi.magnet (magnet)
Address: Owned by 52269167
Token: Automatic via parent device
Support: At least basic

So, miio doesn't discover 52269167 as gateway but somehow sensors connected to the gateway are discovered properly.

I tried miio --inspect and I think it discovered gateway like the following:
miio --inspect 52269167
 INFO  Attempting to inspect 52269167

Device ID: 52269167
Model info: lumi.gateway.v3 (gateway)
Address: 192.168.31.207 
Token: 607a194ccaf7e9c7d8fca7ab8371630d via auto-token
Support: At least basic

Firmware version: 1.3.1_141
Hardware version: MW300
MCU firmware version: 0141

WiFi: BSGSNet (F0:B4:29:F6:23:D4) RSSI: -57
WiFi firmware version: SD878x-14.76.36.p84-702.1.0-WM

Remote access (Mi Home App): UDP

Here, I have still no idea whether my one is v2 or v3. Its model name is DGNWG02LM which is printed in the back of gateway. One thing to notice is firmware version. At the moment, I deliberately didn't update to the recent firmware 1.4.1_145.0141. Maybe that could be the reason why miio fails to discover it as gateway.

However, the gateway replies the list of sub devices well like the following:
miio --control 52269167 --method get_device_prop --params '["lumi.0","device_list"]'
 INFO  Attempting to control 52269167

 INFO  Got result:
[
  "lumi.158d000157382e", // lumi.sensor_ht
  10,
  1,
  0,
  2,
  "lumi.158d0001874c26", //lumi.motion (motion)
  2,
  1,
  0,
  11,
  "lumi.158d00012ca74c", //lumi.switch (controller)
  1,
  1,
  0,
  10,
  "lumi.158d00014d3826", //lumi.magnet (magnet)
  3,
  1,
  0,
  10
]

Thanks for your sharing again :)

**Comment by aholstenson** [comment]
Thanks for your report! This is because the current version only uses a lookup of a hostname to determine the model of a device. When it actually connects to the device (as --discover does) it sees that is a gateway and that automatically discovers the subdevices.

I'm currently thinking about a new way to determine the model and tracking the progress in #27.

**Comment by pointbre** [comment]
Thanks for your reply. In order to help you figure out the best way to discover gateway, I'd like to share what I found: 

https://github.com/louisZL/lumi-gateway-local-api

It is not a code repository but a document one. There are many .md files written in Chinese but I believe you can use google translation. The repository seems to have all of detail in regard to gateway and I wish it would help you. 

In regard to gateway discovery, maybe you can use heartbeat message which is sent by gateway repeatedly(perhaps every 10 seconds) like the following:

{"cmd":"heartbeat","model":"gateway","sid":"286c078911ea","short_id":"0","token":"BaY3p3mZ90Jszl3O","data":"{\"ip\":\"192.168.31.207\"}"}

It does't say gateway 2 or 3 but at least it says "I'm gateway" and ip address too. The packet is sent from 4321 port of gateway to 9898 of 224.0.0.50 via udp multicast when local communication mode is on.

**Comment by aholstenson** [comment]
Thanks, that's a good resource and is how support for the gateway is currently implemented.

The gateway version is determined by the model info, and based on the inspect you posted it looks like you have the 3rd version.

**Comment by aholstenson** [comment]
Version 0.15.x has implemented better support for discovery the model of a device. Hopefully this will have resolved this issue.
