### ISSUE TITLE
[Question / Request] Resolve multiple devices

### ISSUE THREAD

**Issue by jghaanstra** [aholstenson/miio#29]
First all, great work. Second, this is not an issue and might not even be a feature request. Sorry for that.

I'd like to integrate this library in an app for a home domotica controller (Homey by Athom). I'd like to know if it's possible to resolve multiple device with their own handle simultaneously when initializing this app for the home domotica controller instead of having to resolve the device every time a command is triggered.

For instance when someone uses a purifier and a vacuum cleaner both devices can be resolved and have their own commands. I can get this to work to resolve the device every time a command is given but I'd rather resolve all devices once upon initialization of my own app.

Hope it makes sense.

**Comment by aholstenson** [comment]
Thanks! The closest that exists right now is the `miio.devices()` method that discovers all devices on the local network and connects to them (if the token is available either via auto-token or manually set via `miio` command). It emits events for when a device is found or when it is no longer available on the network. You can safely keep the handle of a device received in the `available` event.

Does that come close to what you need?

**Comment by jghaanstra** [comment]
It might but I lack the programming skills to create a working example. I used the miio.devices() example code form the README (which contains a little error where it is declared as miio.devices but uses browser.on etc.) but cant get it to resolve my vacuum cleaner as it hides it's token. I dont know how to use the miio.devices() method while manually setting the token.

I did fiddle with the miio.createDevice() method and resolve my cleaner twice under it's own name. I believe that solves my problem and will enable me to manually create the devices based on the device settings previously saved within my own app. The example code below works, I did not even have to manually initialize the device for the find command to be fired twice. Any downsides to this?
`const miio = require('./lib');

const device1 = miio.createDevice({
	address: '192.168.0.133',
	token: '69..removed..64',
	model: 'rockrobo.vacuum.v1'
});

device1.find();

const device2 = miio.createDevice({
	address: '192.168.0.133',
	token: '69..removed..64',
	model: 'rockrobo.vacuum.v1'
});

device2.find();`

**Comment by jghaanstra** [comment]
Ok, thanx for the information. Running the miio app on the domotica controller is indeed not possible.

Feeding tokens to the miio.devices() method and manually setting device handles for these tokens would  enable me to create one device handle for every user added device upon initialization of my own app and keep things clean. But for now I'll go with creating a new device handle for every new command or status request and destroy() this handle afterwards.

Thanx again for this great library.
