### ISSUE TITLE
Miio --discover does not find gateway

### ISSUE THREAD

**Issue by brunoshine** [aholstenson/miio#31]
Hi all,

i'm trying to get miio to work with my gateway with no success. I've got a lumi.gateway.v3  but the
`miio --discover` just runs forever without any output.

I've tried other libraries and I was able to connect to the gateway and get info from de sub devices.

I've tried to discover the gateway with the developer mode ON and with both local area network communication protocol ON and OFF.

any thoughts?

thanks.

**Comment by aholstenson** [comment]
Thanks for the report! The device discovery used in `miio --discover` does not depend on the local developer connection on the gateway, it instead uses a broadcast to the port 54321 that devices respond to. It will scan every few minutes until you close it by pressing Ctrl+C.

I have a few questions that might help with figuring out why it doesn't work:
* Are you running the latest release of the command line app?
* What firmware version is your gateway running? You can find it in the Mi Home app on the same page where the Local Developer API is configured.
* Do you have any special network configuration? Especially something that could block UDP broadcasts such as having the gateway on a separate IP-range?

**Comment by brunoshine** [comment]
Hi,

about your questions:

**Are you running the latest release of the command line app?**
I believe so. I've installed the miio last night.
**What firmware version is your gateway running? You can find it in the Mi Home app on the same page where the Local Developer API is configured.**
I'm running the 1.4.1_146
**Do you have any special network configuration? Especially something that could block UDP broadcasts such as having the gateway on a separate IP-range?**
Don't think so.

Let me know if you need any more details.

Thanks.

**Comment by aholstenson** [comment]
Thank you for the details. I'm not sure what is causing the broadcast that the discovery uses to fail for your setup. I have a few network related changes coming up so I'll investigate a bit when I'm making those changes.

**Comment by aholstenson** [comment]
Closing this issue, moving all discovery issues into #92.
