### ISSUE TITLE
yeelink.light.bslamp2

### ISSUE THREAD

**Issue by codyc1515** [aholstenson/miio#320]
Yeelight Bedside Lamp 2 not appear to be supported when I run the discover command I get the following result:

pi@Homebridge4:~ $ miio discover
 INFO  Discovering devices. Press Ctrl+C to stop.

Device ID: 106365637
Model info: Unknown
Address: 192.168.XXX.XXX
Token: ???
Support: Unknown

**Comment by thehairy** [comment]
When adding the token to it it says 

Device ID: 472195883
Model info: yeelink.light.bslamp2
Address: 192.168.178.50
Token: e5f0a5b18d9624d5848c7f97a9fbb292 via stored token
Support: At least generic

But none of the stuff described anywhere seems to work.

**Comment by codyc1515** [comment]
Looks like this project is abandoned. Closing.
