### ISSUE TITLE
[Request / Question] possible to bind wifi settings without mii app?

### ISSUE THREAD

**Issue by Zontex** [aholstenson/miio#33]
Hi,
I'm wondering if it's possible to make the initial connection (the one that connect Mi device to your Wifi network, using the app "tutorial) automatically using miio framework?
I mean, eliminate completely the usage of mii app using that method?
Thanks a lot.

**Comment by aholstenson** [comment]
Hi!

It is indeed possible to use the `miio` command line app to do this, you can read about it under the section Configuring a new device in [Device management](https://github.com/aholstenson/miio/blob/master/docs/management.md).

It seems to work fine with the devices I have access to, but an important note is that the device will no longer be available to use from the Mi Home app if this method is used. But if you're looking to using this method you probably don't want that anyway.

**Comment by Zontex** [comment]
@aholstenson You're the best.
do you have any plans to translate the code into other languages? I forked your project and i plan to convert it into python on my free time, but another big plan would be to convert it into C language, what do you think?

**Comment by aholstenson** [comment]
Porting it to other languages sounds awesome. I have no plans do any ports myself at the time, so go ahead and do whatever you feel like!
