### ISSUE TITLE
Catch a click on a lumi.switch

### ISSUE THREAD

**Issue by Shuunen** [aholstenson/miio#36]
Hi there :)

I tried to catch a click on my switch & spend almost an hour trying everything with miio but nothing worked :(

I just discovered https://github.com/marvinroger/node-lumi-aqara few minutes ago and test this snippet :

```js
const Aqara = require('lumi-aqara')
const aqara = new Aqara()
aqara.on('gateway', (gateway) => {
    console.log('Gateway discovered')
    gateway.on('ready', () => console.log('Gateway is ready'))
    gateway.on('subdevice', (device) => {
        if (device.getType() === 'switch') {
            console.log('Found switch :)')
            console.log(`  Battery: ${device.getBatteryPercentage()}%`)
            console.log(`  SID: ${device.getSid()}`)
            device.on('click', () => console.log(`${device.getSid()} is clicked`))
        }
    })
})
```
Then this is the output I just had :
```
Gateway discovered
Gateway is ready
Found switch :)
  Battery: 53.6%
  SID: 15xxxd0
```
Then I clicked on my switch and tadaaa : `15xxxd0 is clicked`

So now I wonder what I missed here when using miio ?

What's the proper way to do this ?

Thanks

**Comment by aholstenson** [comment]
Thanks for the report.

The proper way to do this via `miio` is either to connect to the gateway via `miio.device` or use discovery:

A call to `miio.devices()` would return a browser that should find your gateway and any devices connected to it. You can filter the results and add listeners to anything that is of type `controller` to listen for actions:

```javascript
const devices = miio.devices({
  filter: reg => reg.type == 'gateway' || reg.type == 'controller'
});

devices.on('available', reg => {
  const device = reg.device;
  if(! device) {
    console.log(reg.id, 'could not be connected to');
    return;
  }

  console.log('Connected to', device);
  if(device.type === 'controller') {
     // This is a controller such as a switch, cube or wall mounted switch
     device.on('action', action => console.log(action.id));
  }
});
```

That should get you started! To help with debugging its also a good idea to run `miio --discover` to make sure that the library can see your gateway and the devices connected to it.

**Comment by Shuunen** [comment]
This snippet works :)
But in my case, I was using the snippet examples on the main [readme](https://github.com/aholstenson/miio/blob/master/README.md) and it was not working because of this part : 
```
 if (!reg.token) {
        console.log(reg.id, 'hides its token');
        return;
    }
```
Because all subdevices were hidding their tokens, it was always exiting before listening for action event...

Why exiting if no token ? Because finnaly even with no token, the library manage to detect devices events

Using a simpler snippet example like this would have been an easier way to start with the miio library  : 
````
const devices = miio.devices()
devices.on('available', reg => {
    const device = reg.device
    if (!device) {
        console.log(reg.id, 'could not be connected to')
        return
    }
    console.log('Connected to', device.type)
    device.on('propertyChanged', e => console.log('Property "' + e.property + '" changed from ' + e.oldValue + ' to ' + e.value))
    device.on('action', action => console.log('Action detected : ' + action.id))
})
````

**Comment by aholstenson** [comment]
Thanks! I'll update the README to be a bit clearer about subdevices not having tokens.
