### ISSUE TITLE
Documentation on protocol/devices

### ISSUE THREAD

**Issue by Bluebie** [aholstenson/miio#4]
Is there any documentation on how these devices work? How do you for example, figure out the properties available?

**Comment by aholstenson** [comment]
https://github.com/OpenMiHome/mihome-binary-protocol has documentation on how the protocol works.

I've done packet capturing on my router and then I've used the Mi Home app to perform a few actions. It works, but it's not a good way to do it, I've been thinking about trying BlueStacks + Wireshark instead -
 as described in the readme of this project: https://github.com/jghaanstra/com.robot.xiaomi-mi

**Comment by aholstenson** [comment]
I've just added a bit more documentation on how to figure out commands for devices. It can be found in `docs/protocol.md`.
