### ISSUE TITLE
Xiaomi Philips Bulb

### ISSUE THREAD

**Issue by deennoo** [aholstenson/miio#43]
Hi there,

Continuing test Xiaomi Device, i have a Xiaomi Philips Bulb : http://www.gearbest.com/smart-lighting/pp_644095.html

app spoke using udp 54321, and this allow udp packet sender order.

How to help you ?

**Comment by aholstenson** [comment]
Thanks, haven't seen that model. A good start is [Missing devices](https://github.com/aholstenson/miio/blob/master/docs/missing-devices.md) for what is needed to support it.

In short: Run `miio --discover` and look for the following:
* The model id from the output
* If the token for the device displayed N/A or a hex value (don't include the hex value)

In this case the model id is the most important thing to start with. If you do not see the model id, try using `miio --inspect idOfDeviceHere` instead. If you're in luck it might say that its a Yeelink-device and those are quite easy to add support for.

If not you can look into creating a packet capture to reverse engineer the commands used for, see [Protocol and commands](https://github.com/aholstenson/miio/blob/master/docs/protocol.md) for details about that.

**Comment by deennoo** [comment]
made some test : 
miio --discover give : 

```
Device ID: 60689031
Model info: Unknown
Address: 192.168.0.208
Token: ???
Support: Unknown

```
Miio --inspect idofdevice

`pi@raspberrypi:~ $ miio --inspect 60689031
 INFO  Attempting to inspect 60689031
 ERROR  Can't connect to device, token could not be found
`

Using packet capture : 
looks like sending order need to be close from a previous one send with the app. 
Looks like there is a time stamp on the orde who valid it

**Comment by deennoo** [comment]
FYI

```
pi@raspberrypi:~ $ miio --inspect 47584928
 INFO  Attempting to inspect 47584928

Device ID: 47584928
Model info: zhimi.airmonitor.v1 (generic)
Address: 192.168.0.xx
Token: 90a5db2af60fdxxx13beed58611dc8bc via auto-token
Support: At least basic

Firmware version: 1.2.9_8030
Hardware version: MW300

WiFi: myssid  (14:0C:76:FB:xx:90) RSSI: -66
WiFi firmware version: SD878x-14.76.36.p84-702.1.0-WM

Remote access (Mi Home App): UDP
```

**Comment by sembsa** [comment]
If you want to use, you may need it https://github.com/sembsa/PhilipsLEDBulb-homekit

**Comment by RomeshA** [comment]
Hi all, I too would like support for this - I have made some progress. The main impediment is that the device doesn't seem to support auto-token, I extracted mine from the sqlite database in my iOS backup (because the token resets whenever it is added to Mi Home). After setting the token

```
miio --update 60685338 --token XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

`miio --discover` shows the model as unknown

```
Device ID: 60685338
Model info: Unknown 
Address: 10.0.0.13 
Token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX via stored token
Support: Unknown
```

but `miio --inspect` has some useful output including the model ID (this matches the one in the sqlite database)

```
romesh@romesh-mbp: Desktop > miio --inspect 60685338
 INFO  Attempting to inspect 60685338

Device ID: 60685338
Model info: philips.light.bulb (generic)
Address: 10.0.0.13 
Token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX via stored token
Support: At least basic

Firmware version: 1.3.0_0032
Hardware version: ESP8266

WiFi: XXXX (XX:XX:XX:XX:XX:XX) RSSI: -68
WiFi firmware version: 1.5.0-dev(7f7a714)

Remote access (Mi Home App): Maybe
```

The functions available in Mi Home are power, brightness, and color temperature. These can be accessed in `miio` with

```
romesh@romesh-mbp: Desktop > miio --control 60685338 --method get_prop --params '["power"]'
 INFO  Attempting to control 60685338

 INFO  Got result:
[
  "on"
]
romesh@romesh-mbp: Desktop > miio --control 60685338 --method get_prop --params '["bright"]'
 INFO  Attempting to control 60685338

 INFO  Got result:
[
  100
]
romesh@romesh-mbp: Desktop > miio --control 60685338 --method get_prop --params '["cct"]'
 INFO  Attempting to control 60685338

 INFO  Got result:
[
  1
]
```

and can be set with

```
miio --control 60685338 --method 'set_power' --params '["off"]'
miio --control 60685338 --method 'set_bright' --params '[100]'
miio --control 60685338 --method 'set_cct' --params '[1]'
```
I've checked that valid power values are "off" and "on", and brightness and color temperature both range from 1 to 100 and can be provided as floats (i.e.  --params '[1.0]' is fine). An error will be returned if bright or cct is <1 or >100

```
romesh@romesh-mbp: Desktop > miio --control 60685338 --method 'set_bright' --params '[0]'
 INFO  Attempting to control 60685338

 INFO  Got result:
[
  "error"
]
```

otherwise result is ok

```
romesh@romesh-mbp: Desktop > miio --control 60685338 --method 'set_bright' --params '[100]'
 INFO  Attempting to control 60685338

 INFO  Got result:
[
  "ok"
]
```

**Comment by aholstenson** [comment]
Thanks to the previously referenced code by @RomeshA support has now been released to NPM in 0.14.0.

**Comment by oshritf** [comment]
Wonder if it still works with new MiHome app version? Previous MiHome version recognized Xiaomi Philips but new one doesnt

**Comment by davidmavec** [comment]
It's there any possibility to update firmware via miio? I have trouble to updating Philips Xiaomi bulb via MiHome, so I want to try with this tool if it's possible.
