### ISSUE TITLE
device.init not reject

### ISSUE THREAD

**Issue by rench** [aholstenson/miio#44]
when i use this way to connect vacuum,
`
device.init()
	.then(() => /* device is ready for commands */)
	.catch(console.error);
`
it always call then,not catch when error happen ,like ip address is not corrent.

**Comment by aholstenson** [comment]
Thanks for the report. `device.init()` is used to setup and load initial properties for most devices. It should load properties from the vacuum as well, at least the first time it is called. Calling `init()` is considered advanced usage together with `miio.createDevice()`. In most cases you should use `miio.device()` if you want to connect via IP.

Can you share how you are creating the initial device handle?

**Comment by rench** [comment]
`    //create device
    let device = miio.createDevice({
      address: this.config.ip,
      token: this.config.token,
      model: 'rockrobo.vacuum.v1'
    });
    if (this.config.sid == undefined) {
      this.config.sid = this.config.ip; //change sid
    }
    device.init()
      .then(() => {
        this.mijia.log.debug('init vacuum done->%s', this.config.ip);
        this.mijia.log.debug('Battery->%s,State->%s,Fan->%s', device.battery, device.state, device.fanPower);
        if (device.state != undefined) {
          this.setVacuum(this.config, device);
          this.devices[this.config.sid] = device;
        } else {
          this.mijia.log.warn('vacuum state undefined, discard to setVacuum');
          device.destroy();
        }
      })
      .catch((err) => {
        this.mijia.log.error(err);
        throw new Error('unable to initialize robot vacuum->%s', this.config.ip);
      });`

if i config a wrong ip address,like `1.1.1.1` , the `then` section will always to be call.
so i have to check the state,if device.state!=undefined ,i will register a homekit accessory.otherwise discard it.

i think ,if it can't init success,will goto `catch` section(promise.reject).

**Comment by aholstenson** [comment]
Looks like any errors during init are being suppressed right now. I'll do a fix for the next release.

In your use case it looks like you probably want to use `miio.device()` instead of `miio.createDevice()` which will connect, resolve the model and initialize the device properly. That method will fail if it can not connect to the device.

**Comment by rench** [comment]
ok,i see.
thank you ~
