### ISSUE TITLE
Can not get device information

### ISSUE THREAD

**Issue by licuhui** [aholstenson/miio#47]
Hi,In the use of this plug-in, I have some problems. Do not know why not get the device information.
The information obtained is as follows:
Device ID: 48562027
Model info: Unknown
Address: 192.168.31.161 

Token: ???
Support: Unknown

Device ID: 1097069
Model info: Unknown
Address: 192.168.31.182 

Token: ???
Support: Unknown

Device ID: 48395663
Model info: Unknown
Address: 192.168.31.69 

Token: ???
Support: Unknown

Device ID: 49371632
Model info: Unknown
Address: 192.168.31.74 

Token: ???
Support: Unknown

Device ID: 54965957
Model info: Unknown
Address: 192.168.31.171 

Token: b0b89550227b8c3caebe86f1359b16a5 via auto-token
Support: Unknown

Device ID: 48282918
Model info: Unknown
Address: 192.168.31.6 

Token: b0b10d0edc28ce80ab1bc4f253a2a96a via auto-token
Support: Unknown

(node:3537) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot set property 'device' of undefined
(node:3537) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:3537) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot set property 'device' of undefined

**Comment by aholstenson** [comment]
Thank you for the report. This is related to the library currently using hostnames to resolve models, which are not always available. When I get around to fixing issue #27, this should work better for devices where the token is known.

**Comment by aholstenson** [comment]
Since miio 0.15.x the model of a device is calculated both via extraction from the hostname and via connecting to the device. For this case where hostnames are unavailable the model should still be displayed for devices that have their token available.

**Comment by rytilahti** [comment]
Just a short side-note, the vacuum will not respond if it hasn't been in contact with the cloud (since restart I suppose). Similarly problematic is the powerstrip (`zimi-powerstrip-v2` over mdns) will respond with broken JSON (there'll be a double comma, breaking some json parsers).
