### ISSUE TITLE
Amazon echo

### ISSUE THREAD

**Issue by Luftloch80** [aholstenson/miio#48]
I want Tor Control the vacuum with Alexa and ha Bridge. How to Start the vacuum with command line?
Or Pause 
Thanks

**Comment by aholstenson** [comment]
Hi, thank you for opening an issue. This library only includes a command line utility for testing things, not for actually controlling them. Support for Amazon Echo and/or such a command line utility is out of scope for this project.

The library can be used to build such an integration, but it should be done in a separate project. There are already a few Homebridge plugins out there and someone might be working on support for Alexa as well.
