### ISSUE TITLE
Air Purifier Sensor data is undefined

### ISSUE THREAD

**Issue by NecronomiconCoding** [aholstenson/miio#49]
`'use strict';

const miio = require('miio');

// Create a new device over the given address
const device = miio.createDevice({
        model: 'zhimi.airpurifier.m1',
        address: '192.168.1.15'
});

function exit() {
process.exit(-1);
}

const value = device.getProperties([ 'aqi', 'temp_dec', 'humidity' ]).promise.then(console.log)
setTimeout(exit, 3000);

`

This  line of code returns  

`
TypeError: Cannot read property 'then' of undefined
    at Object.<anonymous> (/usr/share/openhab2/miairpurifier/monitoring_miairpurifier.js:17:78)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3
`

**Comment by Bluebie** [comment]
`TypeError: Cannot read property 'then' of undefined at Object.<anonymous> ` means '.promise' doesn't exist. when you have .promise, you get `undefined`, and when you try to run `.then()` on that, you get the typeerror. getProperties returns a regular object, not something you can get a promise on. It returns the data immediately.

```js
var value = device.getProperties([ 'aqi', 'temp_dec', 'humidity' ])
console.log(value)
```

should output something like:

```json
{
  "aqi": 3,
  "temp_dec": 20,
  "humidity": 50
}
```

(just guessing at values)

**Comment by aholstenson** [comment]
As commented before, `getProperties` does not return a Promise. Instead it returns the previously loaded properties, using names as defined by the type of device. Refer to the documentation for details about the properties available.

If you want to load properties from the device using the internal names you can use `loadProperties(arrayWithNames)` to do so.

In addition, please do not use `createDevice` unless you have a use case where you need it. If your use case actually requires it, you have to call `init` and wait for it to resolve before doing anything else with the device. It is recommended to use `miio.device()` instead which will resolve the correct model and initialize the device before resolving its promise.
