### ISSUE TITLE
/usr/bin/env: node: No such file or directory

### ISSUE THREAD

**Issue by stfro** [aholstenson/miio#56]
Hello,
I`m trying to integrate my Xiaomi Air Purifier with Domoticz. Followed the instructions to install miio device library and command line utility:

`root@stf-pi:/usr/local# npm install --save miio
npm WARN engine miio@0.13.0: wanted: {"node":">=6.0.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
miio@0.13.0 node_modules/miio
├── appdirectory@0.1.0
├── minimist@1.2.0
├── debug@2.6.8 (ms@2.0.0)
├── mkdirp@0.5.1 (minimist@0.0.8)
└── chalk@1.1.3 (escape-string-regexp@1.0.5, supports-color@2.0.0, ansi-styles@2.2.1, has-ansi@2.0.0, strip-ansi@3.0.1)
root@stf-pi:/usr/local# ls
bin  etc  games  include  lib  man  node_modules  sbin  share  src
root@stf-pi:/usr/local# npm install -g miio
npm WARN engine miio@0.13.0: wanted: {"node":">=6.0.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
/usr/local/bin/miio -> /usr/local/lib/node_modules/miio/cli/index.js
miio@0.13.0 /usr/local/lib/node_modules/miio
├── appdirectory@0.1.0
├── minimist@1.2.0
├── debug@2.6.8 (ms@2.0.0)
├── mkdirp@0.5.1 (minimist@0.0.8)
└── chalk@1.1.3 (escape-string-regexp@1.0.5, supports-color@2.0.0, ansi-styles@2.2.1, has-ansi@2.0.0, strip-ansi@3.0.1)
`
Not sure how to interpret this output. Unfortunately when trying to discover the device:
`root@stf-pi:/usr/local# miio --discover --sync
/usr/bin/env: node: No such file or directory
`
What am I missing? Unfortunately my linux knowledge is limited.

**Comment by Bluebie** [comment]
it sounds like you have an extremely old version of node installed. you should update it.

**Comment by stfro** [comment]
I did an _apt-get update & upgrade_, then _npm update -g miio_, but the results are te same

**Comment by Bluebie** [comment]
`apt-get upgrade` doesn’t get you a recent version of node if you’re running on an old unmaintained version of debian or ubuntu. node 0.10.29 is from 2014. If you don’t want to update your system to a new release, you should be able to get a newer node via launchpad ppa’s or something like that. It’s advisable to update your OS though, as use of miio implies it’s network connected and it’s a good idea to stay up to date with security updates on a linux system.

**Comment by stfro** [comment]
I run the latest version of Raspbian on RPi 3b, so I`m surprised that it was installing such an old version.

I ended up uninstalling nodejs and installing the latest version using:

_curl -sL https://deb.nodesource.com/setup_8.x | sudo bash -
apt-get install nodejs -y_

Then installed miIO Device Library again. Everything works perfectly now.
Thanks @Bluebie for your tips!
