### ISSUE TITLE
Something wrong with token when connection mi-robot-vacuum

### ISSUE THREAD

**Issue by huafengchun** [aholstenson/miio#58]
I cannot connect my vacuum, my homebridge report an error when init this device. Tim2309 found that the token was wrong, [more infomain](https://github.com/seikan/homebridge-xiaomi-mi-robot-vacuum/issues/7)

**Comment by kokarn** [comment]
Duplicate of #40 i believe. Please look over there for additional help

**Comment by aholstenson** [comment]
Looks like a duplicate. Closing this issue. Please refer to #40 for tips on how to get the token of the vacuum.
