### ISSUE TITLE
feature request: initialise without monitoring

### ISSUE THREAD

**Issue by Bluebie** [aholstenson/miio#6]
It currently isn't possible to initialise devices without activating the monitor function. I think monitor should not be activated until an application binds to one of the interfaces which requires it, so it doesn't generate extra traffic when users have no interest in the monitor feature.

At a minimum, the monitor function shouldn't run `_loadProperties()` until a timeout/interval/process.nextTick executes, so users have a chance to `stopMonitoring()` after initialising a device, before it starts generating network traffic.

**Comment by aholstenson** [comment]
There is now an option called `writeOnly` that disables automatic property fetching. The behavior of the specific device types is changed when that flag is set, they will not trigger any property events and reading of property values will return `undefined`.

It's still possible to invoke methods and to manually call `getProperties`.
