### ISSUE TITLE
no output

### ISSUE THREAD

**Issue by mferreira92** [aholstenson/miio#60]
Hi, 

I've installed miio, to find the token for a xiaomi plug

However when I execute miio, i have not output (comand lasts no more than 1 second to execute).

Im running this in a raspian jessie distro. Any feedback of what might be the problem?

**Comment by aholstenson** [comment]
This library uses UDP multicast for discovering devices. A good starting point would be to check that your network does not block these request and that your Pi is on the same network as the device you are trying to reach.

**Comment by aholstenson** [comment]
Closing this issue as the owner of the issue has not answered in a while. Feel free to reopen this issue if you are still having problems!
