### ISSUE TITLE
zhimi-airpurifier-m2 support

### ISSUE THREAD

**Issue by rikki** [aholstenson/miio#61]
I recently got a Xiaomi air purifier 2 (https://www.mi.com/air2/).
the miio --discover shows me that the model of this airpurifier is zhimi-airpurifier-m2
Device ID: 67xxxx76
Model info: Unknown
Address: 10.0.x.xxx (zhimi-airpurifier-m2.local)
Token: 7xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx8 via auto-token
Support: Unknown

But according to this article https://community.home-assistant.io/t/xiaomi-mi-air-purifier-support/14228/15, the original Xiaomi Air purifier 2 has the model "zhimi.airpurifier.m1"

And I think there may be a change that Xiaomi updated their air purifier 2 recently(to zhimi-airpurifier-m2).

Since I use this homebridge plugin https://github.com/seikan/homebridge-mi-air-purifier ,and the plugin uses miio, and the purifier control does not work in homebridge.

So could you please add support for this model air2 in miio

Detailed info about this device 
```
root@raspberrypi:/var/lib/homebridge # miio --inspect 67xxxx76
 INFO  Attempting to inspect 67xxxx76

Device ID: 67xxxx76
Model info: zhimi.airpurifier.m2 (generic)
Address: 10.0.x.xxx (zhimi-airpurifier-m2.local)
Token: 7xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx8 via auto-token
Support: At least basic

Firmware version: 1.2.9_61
Hardware version: MW300

WiFi: xxxxxxxx (xx:xx:xx:xx:xx:xx) RSSI: -31
WiFi firmware version: SD878x-14.76.36.p84-702.1.0-WM

Remote access (Mi Home App): UDP
```

**Comment by aholstenson** [comment]
Thank your for issue report! Do you know if the m2-model has any special features other than those documented under the [information about the Air Purifier](https://github.com/aholstenson/miio/blob/master/docs/devices/air-purifier.md)?

If not I'll just make sure to add the `zhimi.airpurifier.m2` as a mapping to the already existing code.

**Comment by mtom55** [comment]
I'm unable to receive any properties from the device (temp / aqi etc).  I am able to connect using miio.devices to fetch the token.. and then miio.createDevice.. however I can't call any function to return the results

const device = miio.createDevice({
	address: '192.168.100.8',
	token: 'asdfasdfasdf',
	model: 'zhimi.airpurifier.ma2'
});

This one is a 2S if that makes a difference.  I've played with every function that device returns.. i've tried device.temparature, device.call('getProp', 'temperature') and a ton of other stuff

**Comment by szimek** [comment]
I've got `m2` version as well:
```
Model info: zhimi.airpurifier.m2 (generic)
Support: At least basic

Firmware version: 1.2.9_60
Hardware version: MW300

WiFi firmware version: SD878x-14.76.36.p84-702.1.0-WM
```
and it seems to work fine. I'm using it via homebridge plugin and can get temperature, humidity, air quality etc. even via Siri on iOS.

Huge thanks for this library!

**Comment by fschaal** [comment]
I have the same problem as @mtom55. When I discover the device the Model is shown as unknown:

> Device ID: 4xxxxx8                                                                                                                                  
> Model info: Unknown                                                                                                                                  
> Address: 192.168.xx.xx                                                                                                                                
> Token: xxxx via auto-token                                                                                               
> Support: Unknown  

The device name shown in the network is zhimi.airpurifier.m2_miio4xxxxx8

**Comment by neojski** [comment]
miio doesn't seem to work with my Mi Air Purifier 2 either:

miio --discover -v
 INFO  Discovering devices. Press Ctrl+C to stop.

```
Device ID: 5xxx0
Model info: Unknown 
Address: 192.168.0.14 
Token: xxx via auto-token
Support: Unknown
```

**Comment by neojski** [comment]
Actually, it is showing "unknown" model but it connects and works just fine.

**Comment by fschaal** [comment]
@neojski , could you share a code snippet? If I retrieve the device all properties are undefined with token provided or without.

**Comment by markcame** [comment]
I have the same issue i have 2 purifiers but with the last one i'm unable to retrive properties
on discover :

`
Device ID: 7XXXXXXXXXXX9
Model info: zhimi.airpurifier.m2 (generic)
Address: 192.168.2.159 (zhimi-airpurifier-m2_miio747313)
Token: faxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxd via auto-token
Support: At least basic

Device ID: 5xxxxxx5
Model info: zhimi.airpurifier.m1 (air-purifier)
Address: 192.168.2.93 (zhimi-airpurifier-m1_miio542967)
Token: dxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx8 via auto-token
Support: At least basic
`
Issuing inspect command :

`
Device ID: 7xxxxxxx9
Model info: zhimi.airpurifier.m2 (generic)
Address: 192.168.2.159 (zhimi-airpurifier-m2_miio747313)
Token: fxxxxxxxxxxxxxxxxxxxxxxxxxxxxd via auto-token
Support: At least basic

Firmware version: 1.2.9_61
Hardware version: MW300

WiFi: ASUS (FF:XX:XX:XX:XX:28) RSSI: -41
WiFi firmware version: SD878x-14.76.36.p84-702.1.0-WM

Remote access (Mi Home App): UDP
`
with the other purifier instead i am able to retrive the right properties :

`Properties:

  - power: true
  - mode: auto
  - favoriteLevel: 8
  - temperature: 19.5
  - humidity: 43
  - aqi: 14
  - bright: null
  - filterLifeRemaining: 92
  - filterHoursUsed: 262
  - useTime: 15918981
  - led: true
  - ledBrightness: bright
  - buzzer: false
`
With both i'am able to perform connection and send commands.

**Comment by markcame** [comment]
Ok I've found the solution
 in models.js is sufficent to add 

`zhimi.airpurifier.m2': AirPurifier,`

I have another question i've installed on my system miio trought npm but seeems that exist a global and a local copy is this right ?
thanks
Marco

**Comment by aholstenson** [comment]
I've gotten my hands on an air purifier of this model and it looks like it can be treated just as the other air purifiers. One issue I found was that the device init failed for me due to the device sending back weird characters in its JSON-response.

0.14.1 is now available from NPM which should support this model. Thank you for your patience with this issue! Please don't hesitate to open an issue if you find any bugs with the support.

**Comment by aholstenson** [comment]
@mtom55 Sorry, your message disappeared together with the others in this thread. The 2S should be supported in 0.15.3, but if you are using a third-party library that uses miio it will need to be updated to support 0.15.x before it becomes usable for you.

**Comment by ben423423n32j14e** [comment]
Can confirm the 2S is working fine with 0.15.6

I used this command to upgrade: npm install miio@latest --save

Thanks
