### ISSUE TITLE
Record the power consumption of electrical equipment

### ISSUE THREAD

**Issue by giangcoi48k** [aholstenson/miio#68]
I am letting customers rent hundreds of electrical appliances. I use smart socket sockets to manage power consumption, and customers can turn off their devices remotely via the MiHome app. Unfortunately, the smart socket does not record the power consumption details of the devices, so the synthesis is very difficult. I want to write programs to manage device capacity on computer. I found your project, but did not know how to get started. Help me please

**Comment by aholstenson** [comment]
To use this project you need to have an understanding about JavaScript and Node. The documentation in the README and `docs`-folder of the project should be enough to get you started if you have worked with JavaScript before. And the energy consumption seems to be available for some devices.

I'm closing this issue for now. If you have any specific issues when working with the device API feel free to open a new issue.
