### ISSUE TITLE
miio discover doesn't have an update event

### ISSUE THREAD

**Issue by Bluebie** [aholstenson/miio#7]
If a miio device moves to a different IP address, I don't think any event would fire on the miio browser to notify apps of this change?

**Comment by aholstenson** [comment]
No, there is no event right now. I think it's a good idea to add one together with the ability to update the address of a device. I'll add it before the next release.

**Comment by Bluebie** [comment]
you're the best <3

**Comment by aholstenson** [comment]
There is now an event named `update` that is triggered if a device changes address, but there is currently no proper way to update the address of a Device-instance. The best way to handle them right now is to call `destroy()` on the old one and try to connect to the new address via `miio.device()`.

I'm thinking about a few networking changes I want to do, so 0.8.0 might make the entire process easier.

**Comment by Bluebie** [comment]
Ok! I'll implement that soon.
