### ISSUE TITLE
Compatibility with raspberry pi zero?

### ISSUE THREAD

**Issue by DAVIZINH0** [aholstenson/miio#70]
Hello,
Im trying to configure miio with raspberry pi zero and i cant. Someone here can??

**Comment by aholstenson** [comment]
Thank you for your issue! As long as you have installed Node (at least version 6) this library should work. If you are having trouble installing Node try checking out some guides online as it's out of scope to provide that support here.

I'll close this issue for now. If you have any specific issues with installing `miio` via `npm` you can open a new issue or reopen this one with more details such as the output from the install and we can work from there.
