### ISSUE TITLE
about Mi Humidifier 

### ISSUE THREAD

**Issue by nunobet** [aholstenson/miio#71]
Recently, I got a Mi Humidifier and making a homebridge plug-in.
All functions you developed works fine. but I can't find the function to control Target Humidity.
Is there any functions to read or write current TARGET Humidity - not the sensor value but user selected value - ?
Please let me know.

**Comment by aholstenson** [comment]
I don't actually know what command controls the target humidity. I'm very interested in adding support for it. Did you figure out which protocol commands that control the target?

**Comment by Deteorek** [comment]
Hi Nunobet,
I'm very interested in Mi Humidifier homebridge plug-in. Is it possible for you to share it?

**Comment by aholstenson** [comment]
Target humidity is now supported in 0.15.x. Please note that this version has significant changes from 0.14.0 so rewrites will be required of existing code that uses the old version.
