### ISSUE TITLE
Hi I get Cannot find module 'minimist' error...

### ISSUE THREAD

**Issue by Radstake** [aholstenson/miio#72]
module.js:491
    throw err;
    ^

Error: Cannot find module 'minimist'

Any ideas? I already try npm install and npm rebuild
My nodejs version = v8.4.0

Thx!

**Comment by kokarn** [comment]
That's super strange. What command gives you that?

**Comment by Radstake** [comment]
miio --discover

**Comment by kokarn** [comment]
And you have ran `npm install -g miio` before?

**Comment by Radstake** [comment]
of course. i see the module minimist being present with the miio dir as well

**Comment by Radstake** [comment]
any ideas? I'm so wanting to use it..

**Comment by Radstake** [comment]
Works, update npm to 5.5.1, now it works...
