### ISSUE TITLE
Support for door/window sensors (magnet)?

### ISSUE THREAD

**Issue by mirko3000** [aholstenson/miio#76]
Hello,

I saw that the miio library generally seems to correctly identify the door/window sensors (type 'magnet'). But in the properties I could not find anything which looks like the current state (open or closed). Is that property available? Or do I have to monitor for events?

I have the Xiaomi door/window sensors, in the logs I see the type "lumi.magnet".

Best regards,
Mirko

**Comment by aholstenson** [comment]
There should be a property named `open` available on the the device. Looking at the code it seems like its available via `device.property('open')`. The device should also emit an `open` and `close` event when it changes.

**Comment by mirko3000** [comment]
That property seems not to be set, this is what I get:
`Magnet {
  domain: null,
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined,
  model: 'lumi.magnet',
  id: '158d00016ccdae',
  type: 'magnet',
  capabilities: [],
  _properties: {},
  _propertiesToMonitor: [],
  _propertyDefinitions: {},
  _parent: 
   Gateway {
   ....
   }
 }`

**Comment by mirko3000** [comment]
I just tried listening to property change events, here I actually recieve changes to the property "open". Seems that the property is initially null, and only gets set when recieving the first event.

**Comment by mirko3000** [comment]
So question simply is this: is is possible to get the initial state of the magnet sensors? Or does the system only recieve events? I see that even without changes at sometime I recieve some propertyChange events with the correct state - how is that different to the temperature sensors?

Another thing: the property Change events are really good, but without the ID of the device which trigger the change I cannot do anything useful with them. I am listening to all my devices, but simply the changed data does not help. Could you add the device ID to each propertyChange event?

**Comment by mirko3000** [comment]
Another thing I noticed: the magnet sensors always trigger a wrong closing event after exactly 60 seconds - even if the window is still opened. You can see some logs I extracted:
![bildschirmfoto 2017-11-18 um 18 09 05](https://user-images.githubusercontent.com/4167984/32982896-d710de2a-cc8b-11e7-80be-76e21f0f65a9.png)

I checked with the Mi app, here the status is shown correct. It happens for every magnet sensor I have.

**Comment by mirko3000** [comment]
Found the issue: the magnet sensors also send events on other property changes. In my case I recieved a change with "no_close" : 60, which is used to trigger automation after 60 seconds of opened window/door. This event was not handled correctly, resulting in a 'false' open state.
Will send you pull request for my fix.

**Comment by mirko3000** [comment]
https://github.com/aholstenson/miio/pull/77

**Comment by aholstenson** [comment]
Thanks again for helping with this. Fixes for this are available in version 0.15.x, but the API is very different from 0.14 so it might not be directly usable without some work on your end.
