### ISSUE TITLE
miio get wrong token for xiaomi robot vacuum 

### ISSUE THREAD

**Issue by 0xcb49** [aholstenson/miio#78]
node: v8.9.1
miio: 0.14.0
xiaomi robot: 3.3.9_003077

miio --discover --sync can get device info of xiaomi robot. But when I use the token generated by miio, it says timeout.

**Comment by rafale77** [comment]
you have the wrong token. If you have a recent firmware, you cannot use Miio -- discover to sync the token. You will have to go through the other method in the readme

**Comment by realhoffi** [comment]
i had the same problem, do the following steps please:

1. Reset Vacuum(https://docs.google.com/document/d/18FwzI8lTUnP1Sh6f1iDPQyq1oK4q9piZ6_CW0jXaLa4/edit)
2. After reset, connect with your desktop pc  to the WLAN of the robot 
3. do the following command:  miio --discover
4. NOW you got the coorect token!

**Comment by aholstenson** [comment]
Closing this issue as token issues are now tracked in #93.
