### ISSUE TITLE
Wifi Plug and Lumi Plug have different device.type strings?

### ISSUE THREAD

**Issue by Bluebie** [aholstenson/miio#8]
a chuangmi-plug-m1 wifi power plug device has a "switch" type but a lumi gateway plug has a "plug" type, though they are very similar devices, aside from the lumi plug having some extra power usage measurement functionality. Shouldn't they be the same type, or at least, similar words?

**Comment by aholstenson** [comment]
They should but I'm unsure which one is the right one. I'm still leaning towards the type being switch, and that the switches will supports channels. I want the APIs to be almost identical if the type of unit is close enough. Still working a bit on the Lumi Gateway though but I'll probably wrap most of it up within a week or so.

**Comment by aholstenson** [comment]
I've just pushed a new version where this is resolved, I settled on `switch` in the end. Switches now have a capability named `power-channels` and supports one or more channels that can be powered on or off.

Other devices can still be powered on or off as indicated by the capability `power`. When working with your Homebridge project you should probably start checking the capability of devices to determine the services they should expose to HomeKit.

Let me know if the new release causes any issues.
