### ISSUE TITLE
Philips Wifi Bulb discover

### ISSUE THREAD

**Issue by semaf** [aholstenson/miio#80]
Somehow the Bulb will not give me the token. I setup the LED again but still result at token. Are there new firmware which will not allow?

Device ID: xxxxxxxx
Model info: Unknown 
Address: 192.168.0.31 
Token: ???
Support: Unknown

**Comment by aholstenson** [comment]
Hi, thanks for opening this issue. I don't currently have access to a Philips Bulb so I can't say if there is anything special going on with the firmware.

What steps did you do when setting it up?

**Comment by thunderace** [comment]
For get Philips Wifi Bulb token, use this method (source :  [python-miio](https://python-miio.readthedocs.io/en/latest/discovery.html#device-discovery) ) : 
Tokens from backups
Extracting tokens from a Mi Home backup is the preferred way to obtain tokens. For this to work the devices have to be added to the app beforehand before the database (or backup) is extracted.

Creating a backup
The first step to do this is to extract a backup or database from the Mi Home app. The procedure is briefly described below, but you may find the following links also useful:

https://github.com/jghaanstra/com.xiaomi-miio/blob/master/docs/obtain_token_mirobot_new.md
https://github.com/homeassistantchina/custom_components/blob/master/doc/chuang_mi_ir_remote.md
Android
To do a backup of an Android app you need to have the developer mode active, and your device has to be accessible with adb.

Todo
Add a link how to check and enable the developer mode. This part of documentation needs your help! Please consider submitting a pull request to update this.

After you have connected your device to your computer, and installed the Android developer tools, you can use adb tool to create a backup.

adb backup -noapk com.xiaomi.smarthome -f backup.ab
Note
Depending on your Android version you may need to insert a password and/or accept the backup, so check your phone at this point!

If everything went fine and you got a backup.ab file, please continue to Extracting tokens.

Apple
Todo
This part of documentation needs your help! Please consider submitting a pull request to update this.

See https://github.com/jghaanstra/com.xiaomi-miio/blob/master/docs/obtain_token_mirobot_new.md#ios-users for instructions how to extract a database from the app.

Extracting tokens
Now having extract either a backup or a database from the application, the miio-extract-tokens can be used to extract the tokens from it.

At the moment extracting tokens from a backup (Android), or from an extracted database (Android, Apple) are supported.

Encrypted tokens as recently introduced on iOS devices will be automatically decrypted. For decrypting Android backups the password has to be provided to the tool with --password <password>.

Please feel free to submit pull requests to simplify this procedure!

$ miio-extract-tokens backup.ab
Opened backup/backup.ab
Extracting to /tmp/tmpvbregact
Reading tokens from Android DB
Gateway
        Model: lumi.gateway.v3
        IP address: 192.168.XXX.XXX
        Token: 91c52a27eff00b954XXX
        MAC: 28:6C:07:XX:XX:XX
room1
        Model: yeelink.light.color1
        IP address: 192.168.XXX.XXX
        Token: 4679442a069f09883XXX
        MAC: F0:B4:29:XX:XX:XX
room2
        Model: yeelink.light.color1
        IP address: 192.168.XXX.XXX
        Token: 7433ab14222af5792XXX
        MAC: 28:6C:07:XX:XX:XX
Flower Care
        Model: hhcc.plantmonitor.v1
        IP address: 134.XXX.XXX.XXX
        Token: 124f90d87b4b90673XXX
        MAC: C4:7C:8D:XX:XX:XX
Mi Robot Vacuum
        Model: rockrobo.vacuum.v1
        IP address: 192.168.XXX.XXX
        Token: 476e6b70343055483XXX
        MAC: 28:6C:07:XX:XX:XX

**Comment by aholstenson** [comment]
Closing this issue as problems with tokens are now tracked in #93.

**Comment by wilensky** [comment]
`adb backup -noapk com.xiaomi.smarthome -f backup.ab` for **Philips Wifi Bulb** works with **MiHome App v5.0.6** (_later app version doesn't store token in db_).
