### ISSUE TITLE
cannot use getProperties to get the properties, but miio commend can get properties, how to fixed?

### ISSUE THREAD

**Issue by yestop** [aholstenson/miio#82]
cannot use getProperties to get the properties, but miio commend can get properties, how to fixed?

use 

miio --control 192.168.2.119  --method get_prop --params '["power", "mode", "aqi", "temp_dec", "humidity" ]'
 INFO  Attempting to control 192.168.2.119

 INFO  Got result:
[
  "on",
  "auto",
  10,
  215,
  68
]

use  test.js

#!/usr/bin/node
/* eslint-disable */

// Set path to node modules miio
const miio = require('miio');

function exit() {
process.exit(-1);
}

miio.device({
        address: '192.168.2.119'
		
}).then(device => {
                stats = device.getProperties(['power', 'mode', 'aqi', 'temp_dec','humidity' ])
                console.log(stats);
                process.exit();
})

return
{ power: undefined,
  mode: undefined,
  aqi: undefined,
  temperature: undefined,
  humidity: undefined }

**Comment by aholstenson** [comment]
Thanks for opening this issue! What model is the device you are trying to control? Could you provide the output `miio --inspect deviceIdHere`? Just remove the token and WiFi-info and it should be safe to post here.

**Comment by aholstenson** [comment]
Closing this issue as it's unclear what type of device is being controlled and it's been a while without a response. Please feel free to reopen the issue if you are still having problems with this!
