### ISSUE TITLE
[Support] Trying to understand powerChannels, power-load and power-usage

### ISSUE THREAD

**Issue by jghaanstra** [aholstenson/miio#83]
Without actually owning a Xiaomi Power plug or strip I'm trying to implement support in another app using this miio library. So I cant really test anything and I have to do everything based on the docs but I'm getting stuck. Could someone show me some working code on how to use the powerChannels and how to get the loadPower and powerConsumed from both the plug (one socket) and strip (for multiple sockets).

**Comment by aholstenson** [comment]
Power channels were dropped from version 0.15 as they were a bad design decision. In 0.15.0 most devices that had power channels now implement power switching directly, such as the plugs and power strips. The Aqara wall switches (LL and LN versions) expose two children that control their individual "channels".

Those would be used something like this:
```
// Get the first child/channel
const ch0 = lightSwitch.child('0');
ch0.setPower(true)
  .then(handleResultHere)
  .catch(handleError);
```

The docs should be updated to reflect this, with both examples and links to more detailed docs. Feel free to open a new issue if you are having issues with this in 0.15!
