### ISSUE TITLE
could you add a --help parameter to miio cli?

### ISSUE THREAD

**Issue by cissusnar** [aholstenson/miio#85]
miio command is very hard to find parameter, exp. 
```
miio --control  192.168.2.204 --method
 INFO  Attempting to control 192.168.2.204

 ERROR  Encountered an error while controlling device

Error was:
Method `true` is not supported
```
I don't know which method is supported, and I don't know miio have a parameter that is --control
could you add a --help parameter?

**Comment by aholstenson** [comment]
Thanks for opening this issue!

That sounds like a good idea, due to some other changes the miio-command is going to be rewritten. As part of that I'll add a help command.

**Comment by aholstenson** [comment]
The command line client has been rewritten in 0.15.0 and now features a help command.
