### ISSUE TITLE
Delay using Binding, OpenHab2 & Alexa

### ISSUE THREAD

**Issue by crockernr** [aholstenson/miio#88]
Anyone else experienced a large delay when using a combination of this binding, Open Hab2 and Alexa.
I am using this binding for Xiaomi Mi Smart Plugs and when using Alexa there is a delay after she has said the device is not responding.. (around 30 seconds) then the event is triggered.

No other Bindings I am using have delays when using the same combination (OpenHab and Alexa) for example I am using the default Xiaomi Binding for the Gateway and can turn the light on this instantly.

If I set up a sitemap to include the Smartplug using this binding this response is fine when just using OpenHab switches and manually triggering the event...

**Comment by aholstenson** [comment]
Thanks for opening an issue!

This might be both an issue in the binding and in this library. I'm not familiar with the binding, does it have a its source available somewhere so its possible to see how it uses `miio`?
