### ISSUE TITLE
Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by miklosandras** [aholstenson/miio#9]
Today, I updated the npm module to the latest.

I got this error on all request:

root@raspberrypi:/usr/share/openhab2/miairpurifier# miio --discover
/usr/lib/node_modules/miio/cli/index.js:86
                let out;
                ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3
root@raspberrypi:/usr/share/openhab2/miairpurifier#

Would you please help me? May I do wrong anything?

Thank you in advance.

**Comment by Bluebie** [comment]
installing node 7.2.0 or newer will fix this issue. Otherwise you can try running node with the --use-strict option.

**Comment by miklosandras** [comment]
Nodejs upgraded to version 7. Now everything is working well :) Thank you @Bluebie

**Comment by aholstenson** [comment]
Thanks for the report! Glad you were able to resolve it by upgrading Node. I think the minimum Node version is 6.x right now, and I'm targeting the LTS release (6.10.2) and newer versions. I'll add a blurb to the documentation and update `package.json` to reflect this requirement.

**Comment by miklosandras** [comment]
Previous my nodejs version was the latest 5. 
Thank you this great npm module, waiting for that long time ago.
