### ISSUE TITLE
'unavailable' event never called

### ISSUE THREAD

**Issue by thunderace** [aholstenson/miio#90]
First, thank's for your work.
With the miio.devices() example, the 'unavailable' event is never called for a xiaomi philips bulb.
The 'unavailable' event is correctly raised by tinkerhub-discovery/lib/basic.js(105)...

**Comment by aholstenson** [comment]
Thanks for opening this issue! The removal of devices isn't well tested at the moment, and I want to rework discovery for the next release (0.16.x). I'm not sure when I'll get around to it, but this is definitely something I want to fix.

**Comment by thunderace** [comment]
Fixed in the last release.  I don't know how...

**Comment by TiS** [comment]
@thunderace, @aholstenson - please. reopen this one. I'm having same problem with Air Purifier 2. Tinkerhub emits event, but it does not go up to the miio.devices().
