### ISSUE TITLE
Is dwaal storage path constant or it can be changed?

### ISSUE THREAD

**Issue by surik00** [aholstenson/miio#98]
Hello
I've updated to 0.15.1 and faced a new problem: I cannot use miio library running read-only filesystem.
Running with `DEBUG=*` showed an error: ` dwaal Opening storage connection to /root/.local/share/abstract-things/storage +0ms` ([full bash paste is here if necessary](https://pastebin.com/G0wZcx8Z))

I found that it is [on this line](https://github.com/aholstenson/dwaal/blob/e25c170f2b594c0d091737e4dec969d3a1d3d7db/index.js#L31) in dwall repo.

At first I tried to find `Storage` or `dwaal` imports but couldn't. So I decided to change filepath in miio: I tried to replace `dirs.userData()` on lines [21](https://github.com/aholstenson/miio/blob/c39cbf0e65e493e2987fb0cad4fc4ea8a232e45d/lib/tokens.js#L21) and [116](https://github.com/aholstenson/miio/blob/c39cbf0e65e493e2987fb0cad4fc4ea8a232e45d/lib/tokens.js#L116) with my path `/root/usb/tests/miiotest/miio-storage`, but that didn't help too :(

Can you help me to provide path for storage? And it'll be nice if users could do it after importing miio, for example like this:
``` javascript
const miio = require('miio');
miio.setStorage('/my/prefered/path/')
```

P.S. node version is `v9.4.0`, npm version is `5.6.0`
miio installed using ` npm install --prefix . miio`

**Comment by surik00** [comment]
P.P.S. Of course this problem can be solved using symbolic links. Like this:
``` bash
root@minibian[rw]:~/usb/tests/miiotest$ mkdir miio-storage/storage
root@minibian[rw]:~/usb/tests/miiotest$ rm -r /root/.local/share/abstract-things/storage/
root@minibian[rw]:~/usb/tests/miiotest$ ln -s /root/usb/tests/miiotest/miio-storage/storage/ /root/.local/share/abstract-things/
root@minibian[rw]:~/usb/tests/miiotest$ ls -la /root/.local/share/abstract-things/
total 8
drwxr-xr-x 2 root root 4096 Jan 24 15:11 .
drwxr-xr-x 4 root root 4096 Jan 23 21:48 ..
lrwxrwxrwx 1 root root   46 Jan 24 15:11 storage -> /root/usb/tests/miiotest/miio-storage/storage/
```
And after it everything works well. But is there a way to provide storage path in code?

**Comment by aholstenson** [comment]
Thank you reporting this! The path was hardcoded as it stores data in the user data directory. The feature using dwaal was removed in 0.15.2.

The token file is also stored in a user data directory and might cause similar issues for you.

**Comment by surik00** [comment]
So will there be a way to change default path? It'll be nice.
I've provided a symbolic link (as shown above) and now it works on the latest release (0.15.2).
