### ISSUE TITLE
Do you think it's funny to play language games?

### ISSUE THREAD

**Issue by Zzm317** [aholstenson/miio#99]
Why change miio.Device to miio.device?

**Comment by aholstenson** [comment]
Hi! `miio.Device` was an undocumented and unsupported feature and `miio.device()` has always been the recommended way to create a device handle. Version 0.15.x is a major rewrite and lots of the undocumented features were removed, including the ability to access the Device class.

Please refer to the documentation for info about the new API, and feel free to open issues if you encounter any bugs or have questions about the new API!
